apiVersion: v1
kind: Secret
metadata:
  name: azure-config-file
data:
  azure.json: #{AZURE-CONFIG-JSON}#

---

apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
data:
  SubscriptionID: #{AZURE-SUBSCRIPTION-ID}#
  ClientID: #{AZURE-CLIENT-ID}#
  ClientSecret: #{AZURE-CLIENT-SECRET}#
  TenantID: #{AZURE-TENANT-ID}#

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: externaldns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: externaldns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldns
subjects:
- kind: ServiceAccount
  name: externaldns
  namespace: #{NAMESPACE}#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externaldns
spec:
  selector:
    matchLabels:
      app: externaldns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: externaldns
    spec:
      serviceAccountName: externaldns
      containers:
      - name: externaldns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        env:
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                name: azure-credentials
                key: SubscriptionID
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: azure-credentials
                key: ClientID
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: azure-credentials
                key: ClientSecret
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: azure-credentials
                key: TenantID
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=#{AZURE-DNSZONE-DOMAINFILTER}#
        - --provider=azure-private-dns
        - --azure-resource-group=#{AZURE-DNSZONE-RESOURCEGROUP}#
        - --azure-subscription-id=#{AZURE-DNSZONE-SUBSCRIPTIONID}#
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: azure-config-file
