apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop-deployment
spec:
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: bkimminich/juice-shop
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: juiceshop-service
spec:
  type: ClusterIP
  selector:
    app: juiceshop
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juiceshop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "crazyjuiceshop.azurefd.net"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juiceshop-service
                port:
                  number: 80
    - host: "crazyjuiceshop.udacity.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juiceshop-service
                port:
                  number: 80